config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'companies#index'

  get 'recentworks/:days' => 'works#index'

  get 'timetrackerproject/:slug' => 'projects#show'

  resources :companies
  resources :projects
  resources :works
  resources :forms

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
	has_many :projects

	validates :name, length: { minimum: 5 }

	def to_s
		name
	end

end

app/models/form.rb
class Form < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :company
	belongs_to :owner, class_name: "User" 
	has_many :works
	has_many :users, :through => :works

	validates :name, length: { minimum: 5 }
	validates :company_id, presence: true
	validates :owner_id, presence: true
	validates :default_rate, numericality: { only_integer: true, greater_than_or_equal_to: 50, less_than: 10000 }

	validates :slug, length: { minimum: 3 }
	validates :slug, uniqueness: true

	scope :lowdefaultrate, -> { where("default_rate < 100") }

	def to_s
		"#{name} (#{company})"
	end

	def self.export_csv(projects)
		CSV.generate() do |csv|
			csv << ['name', 'company', 'default_rate', 'created_at', 'owner', 'most recent work item']
			projects.each do |project|
				csv << [
									project.name,
									project.company,
									project.default_rate,
									project.created_at,
									project.user,
									project.works.order('created_at DESC').first
				]
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	belongs_to :company
	has_many :works
	has_many :forms
	has_many :projects, :through => :works
	has_many :projects_owned, :foreign_key => 'owner_id', :class_name => 'Project'

	validates :fname, length: { minimum: 2 }
	validates :lname, length: { minimum: 5 }
	validates :company, presence: true

	def to_s
		"#{fname} #{lname}"
	end

end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
	

	validates :project_id, presence: true
	validates :user_id, presence: true
	validates :datetimeperformed, presence: true
	validate :date_is_in_past
	validates :hours, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 8 }


	scope :fullday, -> { where("hours >=8")}
	#scope :recent, -> { where("datetimeperformed > '#{Time.now - 7.days}'")}

	def self.recentdays(numdaysago)
		since_date = Time.now - numdaysago.to_i.days
		where("datetimeperformed > '#{since_date}'")
	end

	def date_is_in_past
		if datetimeperformed.present? && datetimeperformed > Time.now
			errors.add(:datetimeperformed, "can't be in the future")
		end
	end

	def to_s 
		"#{user}: #{datetimeperformed.strftime('%m/%d/%Y %H:%M')} - #{hours} hours"
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require'csv'
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	
	before_filter :only_admins_create_update_company, only: [:new, :create, :edit, :update]

	def index
		@companies = Company.all 
	end

	def show
		#render nothing: true
		#render text: 'hey there'
		@company = Company.find(params[:id])
		respond_to do |format|
			format.html # show.html.erb
			format.xml {render xml: @company }
			format.json { render json: @company }
		end
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(params[:company].permit(:name))
		if @company.save
			flash[:notice] = 'Company Created'
			redirect_to @company 
		else
			render 'new'
		end
	end

	def edit
		@company = Company.find(params[:id])
	end


	def update
		@company = Company.find(params[:id])

		if @company.update(params[:company].permit(:name))
			redirect_to @company 
		else
			render 'edit'
		end
	end

	def only_admins_create_update_company
		redirect_to companies_path, :alert => 'Only admins can create/modify a company' unless current_user.admin
	end
	
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

	def index
	end

	def new
		@form = Form.new(params[:form])
		@form.user = current_user
		@form.save
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@projects = Project.all 
		respond_to do |format|
			format.html
			format.csv { send_data Project.export_csv(@projects), type: 'text/csv; charset=utf-8; header=present', disposition: 'attachment; filename=contacts.csv' }
		end
	end

	def show
		if (params[:slug])
			@project = Project.find_by slug: params[:slug]
		else
			@project = Project.find(params[:id])
		end
		@work = Work.new
		@work.project = @project
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project].permit(:name, :company_id, :default_rate, :slug))
		if @project.save
			flash[:notice] = 'Project Created'
			redirect_to @project
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])

		if @project.update(params[:project].permit(:name, :company_id, :Default_rate, :slug))
			Usermailer.projectupdated_email(@project).deliver
			flash[:notice] = 'Project Updated'
			redirect_to @project
		else
			render 'edit'
		end
	end


end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

	def index
		if (params[:days])
			@works = Work.recentdays(params[:days]).order('datetimeperformed desc').paginate(:page => params[:page])
		else
			@works = Work.all.order('datetimeperformed desc').paginate(:page => params[:page])
		end
	end

	def show
		@work = Work.find(params[:id])
	end

	def new
		@work = Work.new
	end

	def create
		@work = Work.new(params[:work].permit(:project_id, :datetimeperformed, :hours))
		@work.user = current_user
		if params[:doc]
			uploaded_io = params[:doc]
			File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
				file.write(uploaded_io.read)
				@work.doc = uploaded_io.original_filename
			end
		end
		respond_to do |format|
			if @work.save
				Usermailer.workcreated_email(@work).deliver
				format.html { redirect_to @work, notice: 'Work Created' }
				format.js { }
			else
				format.html { render 'new' }
				format.js { }
			end
		end
	end

	def edit
		@work = Work.find(params[:id])
	end

	def update
		@work = Work.find(params[:id])

		if @work.update(params[:work].permit(:project_id, :datetimeperformed, :hours))
			@work.user = current_user
			flash[:notice] = 'Work Updated'
			redirect_to @work 
		else 
			render 'edit'
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper


	def nav_items
		[
			{
			displaytext: 'Companies',
			controllername: 'companies',
			linkurl: companies_path
			},
			{
			displaytext: 'Projects',
			controllername: 'projects',
			linkurl: projects_path
			},
			{
			displaytext: 'Works',
			controllername: 'works',
			linkurl: works_path
			}
		]
	end

	def display_nav_item(displaytext, controllername, linkurl)
		raw("<li#{controller_name == controllername ? ' class="active"' : ''}>#{link_to displaytext, linkurl} </li>")
	end

	def user_logged_in_msg
		str =''
		str += '<div class="userloggedin">'
		if user_signed_in?
			str += "<p id=""user_info"">#{current_user}<br>#{link_to('Logout', destroy_user_session_path, :method => :delete)}</p>"
		else	
			str += "<p id=""user_info"">#{link_to('Login', new_user_session_path)} | #{link_to('Register', new_user_registration_path)}</p>"
		end
		str += '</div>'
		raw(str)
	end

	def sidebar
		unless ['sessions', 'registrations'].include?(controller_name)
			index_title = "All #{controller_name.capitalize}"
			index_path = "#{controller_name}_path"
			new_title = "New #{controller_name.singularize.capitalize}"
			new_path = "new_#{controller_name.singularize}_path"
			raw("<ul>Helper
				<li>#{link_to index_title, eval(index_path)}</li>
				<li>#{link_to new_title, eval(new_path)}</li>
				</ul>")
		end
	end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/companies/_company.html.erb
<tr>
	<td><%= link_to company, company %></td>
</tr>

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
	<div id="errors">
		<p>Please correct the following <%= pluralize(@company.errors.count, "error") %>:</p>
		<ul>
			<% @company.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for(@company) do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.submit @company.new_record? ? "Create Company" : "Update Company" %>
	</div>
<% end %>

app/views/companies/_sidebar.html.erb
<ul>
	<li><%= link_to 'All Companies', companies_path %></li>
	<li><%= link_to 'New Companies', new_company_path %></li>
</ul>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render 'form' %>

<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/companies/index.html.erb
<h1> Companies: index </h1>

<p> Here are all of the companies: </p>

<%
=begin %>
<ul>
	<% @companies.each do |company| %>
		<li><%= link_to company.name, company %></li>
	<% end %>
</ul>
<%
=end %>

<table>
	<tbody>
		<tr>
			<th>Company Name</th>
		</tr>
		<%= render partial: "company", collection: @companies %>
	</tbody>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p><%= link_to 'Edit Company', edit_company_path(@company) %></p>

<% if @company.projects.size > 0 %>
<table>
	<tbody>
		<tr>
			<th>Project</th>
			<th>Company</th>
		</tr>
		<%= render partial: "projects/project", collection: @company.projects %>
	</tbody>
</table>
<% else %>
	<p>No projects</p>
<% end %>

<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/forms/_form.html.erb
<!DOCTYPE html>
<html>
<head>

    <script type="text/javascript">
window.NREUM||(NREUM={});NREUM.info={"beacon":"beacon-1.newrelic.com","errorBeacon":"bam.nr-data.net","licenseKey":"69c22595ae","applicationID":"3986847","transactionName":"IgsLFhMOVV9RRkwKBwYFCT0ABktWUVkGCBYSSxYKDhY=","queueTime":0,"applicationTime":16,"ttGuid":"","agentToken":null,"agent":"js-agent.newrelic.com/nr-411.min.js"}
    </script>
    <script type="text/javascript">
window.NREUM||(NREUM={}),__nr_require=function(t,n,e){function r(e){if(!n[e]){var o=n[e]={exports:{}};t[e][0].call(o.exports,function(n){var o=t[e][1][n];return r(o?o:n)},o,o.exports)}return n[e].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<e.length;o++)r(e[o]);return r}({D5DuLP:[function(t,n){function e(t,n){var e=r[t];return e?e.apply(this,n):(o[t]||(o[t]=[]),void o[t].push(n))}var r={},o={};n.exports=e,e.queues=o,e.handlers=r},{}],handle:[function(t,n){n.exports=t("D5DuLP")},{}],G9z0Bl:[function(t,n){function e(){var t=l.info=NREUM.info;if(t&&t.agent&&t.licenseKey&&t.applicationID&&p&&p.body){l.proto="https"===f.split(":")[0]||t.sslForHttp?"https://":"http://",i("mark",["onload",a()]);var n=p.createElement("script");n.src=l.proto+t.agent,p.body.appendChild(n)}}function r(){"complete"===p.readyState&&o()}function o(){i("mark",["domContent",a()])}function a(){return(new Date).getTime()}var i=t("handle"),u=window,p=u.document,s="addEventListener",c="attachEvent",f=(""+location).split("?")[0],l=n.exports={offset:a(),origin:f,features:[]};p[s]?(p[s]("DOMContentLoaded",o,!1),u[s]("load",e,!1)):(p[c]("onreadystatechange",r),u[c]("onload",e)),i("mark",["firstbyte",a()])},{handle:"D5DuLP"}],loader:[function(t,n){n.exports=t("G9z0Bl")},{}]},{},["G9z0Bl"]);
    </script>

    <title>Pivotal One Partner Program</title>
    <link href="css/mystyle3.css"
    media="all" rel="stylesheet">
    <script src="application.js"></script>
    <link href="images/favicon.ico" rel=
    "shortcut icon" type="image/vnd.microsoft.icon">
    <meta content="authenticity_token" name="csrf-param">
    <meta content="GO9XTntTWxmED8K3dgL2XFAykiUnXCDQXdFREGj5Scw=" name=
    "csrf-token">
    <script type="text/javascript">
var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-39702075-1']);
    _gaq.push(['_setDomainName', 'gopivotal.com']);
    _gaq.push(['_trackPageview']);

    (function () {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
    })();
    </script>
</head>

<body class="bkg-default-5">
    <div class="background-layer gradient-background"></div>

    <div class="cloud-background"></div>

    <div class="page-wrapper">
        <header class="headers">
            <nav class="navbar navbar-inverse navbar-static-top">
                <div class="container">
                    <div class="navbar-header navbar-brand">
                        <a class="image-logo" href="https://partners.gopivotal.com"></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right lhl">
                        <li class="h4">
                            <a href="https://partners.gopivotal.com/home">Partner Dashboard</a>
                        </li>

                        <li class="h4">
                            <a href="https://partners.gopivotal.com/partners">find a partner</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <form action="https://docs.google.com/a/gopivotal.com/forms/d/1FBctL2twA_N__jawHlEYzFslO9U9_h9T5viZ64sN__c/formResponse" method="POST" id="ss-form" target="_self" onsubmit=""><ol role="list" class="ss-question-list" style="padding-left: 0">
<div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item ss-item-required ss-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1279577883"><div class="ss-q-title">Contact Email
<label for="itemView.getDomIdToLabel()" aria-label="(Required field)"></label>
<span class="ss-required-asterisk">*</span></div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<input type="hidden" name="entry.1279577883" value="" class="ss-q-short" id="entry_1279577883" dir="auto" aria-label="Contact Email  " aria-required="true" required="" title="">
<div class="error-message" id="1323713995_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_878157406"><div class="ss-q-title">Customer Name
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<input type="text" name="entry.878157406" value="" class="ss-q-short" id="entry_878157406" dir="auto" aria-label="Customer Name  " title="">
<div class="error-message" id="73525326_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_27924161"><div class="ss-q-title">Country
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<input type="text" name="entry.27924161" value="" class="ss-q-short" id="entry_27924161" dir="auto" aria-label="Country  " title="">
<div class="error-message" id="1773060945_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_1211667202"><div class="ss-q-title">Approximate Deal Size
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<input type="text" name="entry.1211667202" value="" class="ss-q-short" id="entry_1211667202" dir="auto" aria-label="Approximate Deal Size  " title="">
<div class="error-message" id="1231230039_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_887034487"><div class="ss-q-title">Deal Timing
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<input type="text" name="entry.887034487" value="" class="ss-q-short" id="entry_887034487" dir="auto" aria-label="Deal Timing  " title="">
<div class="error-message" id="975125034_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div> <div class="ss-form-question errorbox-good" role="listitem">
<div dir="ltr" class="ss-item  ss-paragraph-text"><div class="ss-form-entry">
<label class="ss-q-item-label" for="entry_622218318"><div class="ss-q-title">Brief Description of the Opportunity
</div>
<div class="ss-q-help ss-secondary-text" dir="ltr"></div></label>
<textarea name="entry.622218318" rows="8" cols="0" class="ss-q-long" id="entry_622218318" dir="auto" aria-label="Brief Description of the Opportunity  "></textarea>
<div class="error-message" id="1568854780_errorMessage"></div>
<div class="required-message">This is a required question</div>
</div></div></div>
<input type="hidden" name="draftResponse" value="[,,&quot;1249535605058744711&quot;]
">
<input type="hidden" name="pageHistory" value="0">


<input type="hidden" name="fbzx" value="1249535605058744711">

<div class="ss-item ss-navigate"><table id="navigation-table"><tbody><tr><td class="ss-form-entry goog-inline-block" id="navigation-buttons" dir="ltr">
<input type="submit" name="submit" value="Submit" id="ss-submit">
<div class="ss-password-warning ss-secondary-text">Never submit passwords through Google Forms.</div></td>
</tr></tbody></table></div></ol></form>
            </div>
        </main>
        <footer class="page-footer">
            <div class="container">
                <ul class="list-footer mbn">
                    <li>
                        <ul class="list-legal">
                            <li>
                                <a class="link-inverse" href=
                                "http://www.gopivotal.com/privacy-policy">Cookie
                                & Privacy Policy</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <ul class="list-inline lhs">
                            <li>&copy; 2014 Pivotal Software, Inc.</li>

                            <li>All Rights Reserved.</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </footer>
    </div>
</body>
</html>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render 'form' %>

<% content_for :aside do %>
    <%= render 'sidebar' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<header>
		<%= link_to content_tag('canvas', 'TimeTracker', id: 'logocanvas'), root_url %>
		<nav>
			<ul>
				<% nav_items.each do |nav_item| %>
					<%= display_nav_item(nav_item[:displaytext], nav_item[:controllername], nav_item[:linkurl]) %>
				<% end %>
			</ul>
		</nav>
	</header>
	<section id="main">
		<article>
			<% [:notice, :alert].each do |level| %>
				<% if flash[level] %>
					<div class="flash <%= level %>"><%= flash[level] %></div>
				<% end %>
			<% end %>
			<%= yield %>
		</article>
		<aside>
			<%= user_logged_in_msg %>
			<% if content_for?(:aside) %>
				<%= yield :aside %>
			<% else %>
				<%= sidebar %>
			<% end %>
		</aside>
	</section>
	<footer>
		<p>Timetracker is a <em>Sample Company</em> App</p>
	</footer>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
	<div id="errors">
		<p>Please correct the following <%= pluralize(@project.errors.count, "error") %>:</p>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for(@project) do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :company_id %>
		<%= f.collection_select(:company_id, Company.all, :id, :to_s, prompt: true) %>
	</div>
	<div>
		<%= f.label :owner_id %>
		<%= f.collection_select(:owner_id, User.all, :id, :to_s, prompt: true) %>
	</div>
	<div>
		<%= f.label :default_rate %>
		<%= f.text_field :default_rate %>
	</div>
	<div>
		<%= f.label :slug %>
		<%= f.text_field :slug %>
	</div>
	<div>
		<%= f.submit @project.new_record? ? "Create Project" : "Update Project" %>
	</div>
<% end %>

app/views/projects/_project.html.erb
<tr>
	<td><%= link_to project, project %></td>
	<td><%= link_to project.company.name, project.company %></td>
</tr>

app/views/projects/_sidebar.html.erb
<ul>
	<li><%= link_to 'All Projects', projects_path %></li>
	<li><%= link_to 'New Project', new_project_path %></li>
</ul>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/projects/index.html.erb
<h1> Projects: index </h1>

<p> Here are all of the projects: </p>

<%
=begin %>
<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project %></li>
	<% end %>
</ul>
<%
=end %>

<table>
	<tbody>
		<tr>
			<th>Project</th>
			<th>Company</th>
		</tr>
		<%= render partial: "project", collection: @projects %>
	</tbody>
</table>

<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p>Company: <%= @project.company.name %></p>
<p>Default Rate: <%= @project.default_rate %></p>
<p>Slug: <%= @project.slug %></p>
<p>Owner: <%= @project.owner %></p>

<%= link_to 'Edit Project', edit_project_path(@project) %>

<div class="remoteform">
	<h2>Add Work</h2>
	<%= render partial: 'works/form', locals: {doajax: true} %>
</div>


<% if @project.works.size > 0 %>
<table>
	<tbody>
		<tr>
			<th>View</th>
			<th>User</th>
			<th>Project</th>
			<th>Date and Time</th>
			<th>Hours</th>
		</tr>
		<%= render partial: "works/work", collection: @project.works %>
	</tbody>
</table>
<% else %>
<p>No work items. </p>
<% end %>


<% content_for :aside do %>
	<% render 'sidebar' %>
<% end %>

app/views/works/_form.html.erb
<% if @work.errors.any? %>
	<div id="errors">
		<p>Please correct the following <%= pluralize(@work.errors.count, "error") %>:</p>
		<ul>
			<% @work.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<% doajax = false unless (defined? doajax) %>
<%= form_for(@work, remote: doajax, :html => { :multipart => true }) do |f| %>
	<div>
		<%= f.label :project_id %>
		<%= f.collection_select(:project_id, Project.all, :id, :name, prompt: true) %>
	</div>
	<div>
		<%= f.label :datetimeperformed, 'Date/Time Performed' %>
		<%= f.datetime_select :datetimeperformed %>
	</div>
	<div>
		<%= f.label :hours %>
		<%= f.select(:hours, [1,2,3,4,5,6,7,8], prompt: true) %>
	</div>
	<div>
		<%= label_tag :doc, 'Notes (optional)' %>
		<%= file_field_tag :doc %>
	</div>
	<div>
		<%= f.submit @work.new_record? ? "Create Work" : "Update Work" %>
	</div>
<% end %>

app/views/works/_sidebar.html.erb
<ul>
	<li><%= link_to 'All Works', works_path %></li>
	<li><%= link_to 'New Works', new_work_path %></li>
</ul>

app/views/works/_work.html.erb
<tr>
	<td><%= link_to 'View', work %></td>
	<td><%= work.user %></td>
	<td><%= link_to work.project, work.project %></td>
	<td><%= work.datetimeperformed.strftime('%m/%d/%Y %H:%M') %></td> 
	<td><%= work.hours %></td>
<tr>

app/views/works/create.js.erb
<% if @work.errors.any? %>
	$('<div id="errors"><p>Please correct the following <%= pluralize(@work.errors.count, "error") %>:</p><ul><% @work.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %></ul></div>').insertBefore('div.remoteform h2');
<% else %>
	$('div#errors').remove();
	$('<tr><td><%= link_to 'View', @work %></td><td><%= @work.user %></td><td><%= link_to @work.project, @work.project %></td><td><%= @work.datetimeperformed.strftime("%m/%d/%Y %H:%M") %></td><td><%= @work.hours %></td></tr>').insertAfter('tr#headerrow');
<% end %>

app/views/works/edit.html.erb
<h1>Edit Work</h1>

<%= render 'form' %>

<% content_for :aside do %>
	<%= render 'sidebar' %>
<% end %>

app/views/works/index.html.erb
<h1> Works: index </h1>

<p> Here are all of the works: </p>

<%
=begin %>
<ul>
	<% @works.each do |work| %>
		<li><%= link_to work, work %></li>
	<% end %>
</ul>
<%
=end %>
<table>
	<tbody>
		<tr>
			<th>View</th>
			<th>User</th>
			<th>Project</th>
			<th>Date and Time</th>
			<th>Hours</th>
		</tr>
		<%= render partial: "work", collection: @works %>

	</tbody>
</table>

<%= will_paginate @posts %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

<% content_for :aside do %>
	<%= render 'sidebar' %>
<% end %>

app/views/works/show.html.erb
<h1><%= @work.datetimeperformed %></h1>

<p>User: <%= @work.user.fname %> <%= @work.user.lname %></p>
<p>Project: <%= @work.project.name %></p>
<p> Hours: <%= @work.hours %> </p>
<% if @work.doc %>
	<p>Document: <%= link_to @work.doc, "/uploads/#{@work.doc}", :target => "_blank" %></p>
<% end %>

<p><%= link_to 'Edit Work', edit_work_path(@work) %></p>

<% content_for :aside do %>
	<%= render 'sidebar' %>
<% end %>